name: npm publish
on:
  push:
    tags:
      - 'v*'
jobs:
  npm_publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm ci
    - name: Authenticate with registry
      run: echo -e "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
    - run: npm publish
